import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import OAuthCapture from "@/components/OAuthCapture";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log("======================================================OAuthCapture rendered======================================================");

  
  return (
    <html lang="en">
      <body className="bg-background text-foreground"
      >
        <Suspense fallback={null}>
          <OAuthCapture />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
