"use client";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import ChatBot from "@/components/ChatBot";
import { Suspense } from "react";
import OAuthCapture from "@/components/OAuthCapture";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";


const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground"
      >
        <div className="min-h-screen flex flex-col">
        <SessionProvider>
          <ReactQueryProvider>
            <Toaster />
            <Suspense fallback={null}>
              <OAuthCapture />
            </Suspense>
            {children}
          </ReactQueryProvider>
        </SessionProvider>

        <ChatBot />
        <Footer />
        </div>
      </body>
    </html>
  );
}
