import type { Metadata } from "next";
import "./globals.css";
import AdminLayout from "@/components/Sidebar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground"
      >
        <div className="min-h-screen flex flex-col">
        <AdminLayout children={children} />
        {children}
        </div>
      </body>
    </html>
  );
}
